service: s3-to-dynamo-service

frameworkVersion: '3'

provider:
  name: aws
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./

# you can overwrite defaults here
#  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 'dynamodb:*'
          Resource: '*'
functions:
  write-data-in-dynamo:
    image: appimage
    events:
      - s3:
          bucket: csv-folder-0912398123
          event: s3:ObjectCreated:*
