service: data-ingestion-service
useDotenv: true


frameworkVersion: '3'

provider:
  name: aws

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./

# you can overwrite defaults here
#  stage: dev
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 'dynamodb:*'
          Resource: '*'
functions:
  write-data-in-dynamo:
    image: appimage
    environment:
      dynamo_table_name: ${env:DYNAMO_TABLE}

    events:
      - s3:
          bucket: ${env:S3_BUCKET_NAME}
          event: s3:ObjectCreated:*